### ISSUE TITLE
Reduce Nuke range

### ISSUE THREAD

**Issue by Heckle1** [outscale-dev/frieza#186]
Hi team,

As a User when I want to clean my account I firstly want to removed billable resources or ressources with quotas. Secondly I want to clean all my ressources which excludes : ak/sk and keypairs. EIPs are also something I don't want to clean but it's more debatable.

As a conclusion, Frieza is to powerfull as it nukes ak/sk and keypairs. 
Here are my 2 cents  : 
1/ An options of nuke command to avoid cleaning ak/sk and keypairs
2/ Default is to not perform ak/sk + keypair nuke and use options to do it.
3/ An other sub-command such as "mininuke"

Thank you !

**Comment by jerome-jutteau** [comment]
Hi!
Did you see `--only-resource-types` option? 
I agree we are missing something like `--exclude-resource-types` (see #187)

> An other sub-command such as "mininuke"

What do you mean by "mininuke"? Do you think of a new frieza provider targeting Kubernetes resources?

**Comment by Heckle1** [comment]
I've seen the --only-resource-types... afterwards, it was too late, everything was nuked. However this is painful to list every ressources I want to clean, also find out ressource name of the provider is not user friendly (also find out the full list itself is a blurry thing to do)


My suggestion of mininuke is to do the equivalent of "nuke --exclude-resource ak,sk,keypair", nothing related to k8s ^^

**Comment by jerome-jutteau** [comment]
My brain has been washout with kubernetes, I read "minikube"

+1 should mention sub-command on how to list resources in `--only-resource-types` doc

**Comment by jerome-jutteau** [comment]
Closed via https://github.com/outscale-dev/frieza/issues/187
